### ISSUE TITLE
Work in session expiration

### ISSUE THREAD

**Issue by gtaylor** [gtaylor/django-dynamodb-sessions#1]
Figure out how to expire sessions. The first order of business would be to actually store session creation times. We'd probably have to store them as a UNIX Epoch time int, so we can run a simple query to figure out what to purge.

**Comment by Mihai925** [comment]
Hi Greg,

Will you be implementing this feature? If you don't have any plans for it, I'd like to work on it using the UNIX Epoch time to identify the expired sessions. Let me know!

**Comment by gtaylor** [comment]
I guess I should probably close this out! I'm not currently maintaining this package at all, though I'll glance over and merge PRs that *seem* OK. Not really ready to commit to any kind of maintenance since I moved on from the place that uses this long ago.
